// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/api.proto

package org.techfrog.restprotocolbuffers.model;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_restprotocolbuffers_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_restprotocolbuffers_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_restprotocolbuffers_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_restprotocolbuffers_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_restprotocolbuffers_Student_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_restprotocolbuffers_Student_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/resources/api.proto\022\023restprot" +
      "ocolbuffers\"X\n\006Course\022\n\n\002id\030\001 \001(\005\022\023\n\013cou" +
      "rse_name\030\002 \001(\t\022-\n\007student\030\003 \003(\0132\034.restpr" +
      "otocolbuffers.Student\"\200\002\n\007Student\022\n\n\002id\030" +
      "\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030\003" +
      " \001(\t\022\r\n\005email\030\004 \001(\t\0227\n\005phone\030\005 \003(\0132(.res" +
      "tprotocolbuffers.Student.PhoneNumber\032S\n\013" +
      "PhoneNumber\022\016\n\006number\030\001 \001(\t\0224\n\004type\030\002 \001(" +
      "\0162&.restprotocolbuffers.Student.PhoneTyp" +
      "e\"%\n\tPhoneType\022\n\n\006MOBILE\020\000\022\014\n\010LANDLINE\020\001" +
      "B*\n&org.techfrog.restprotocolbuffers.mod" +
      "elP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_restprotocolbuffers_Course_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_restprotocolbuffers_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_restprotocolbuffers_Course_descriptor,
        new java.lang.String[] { "Id", "CourseName", "Student", });
    internal_static_restprotocolbuffers_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_restprotocolbuffers_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_restprotocolbuffers_Student_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Phone", });
    internal_static_restprotocolbuffers_Student_PhoneNumber_descriptor =
      internal_static_restprotocolbuffers_Student_descriptor.getNestedTypes().get(0);
    internal_static_restprotocolbuffers_Student_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_restprotocolbuffers_Student_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
