// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/api.proto

package org.techfrog.restprotocolbuffers.model;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:restprotocolbuffers.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string course_name = 2;</code>
   */
  java.lang.String getCourseName();
  /**
   * <code>string course_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>repeated .restprotocolbuffers.Student student = 3;</code>
   */
  java.util.List<org.techfrog.restprotocolbuffers.model.Student> 
      getStudentList();
  /**
   * <code>repeated .restprotocolbuffers.Student student = 3;</code>
   */
  org.techfrog.restprotocolbuffers.model.Student getStudent(int index);
  /**
   * <code>repeated .restprotocolbuffers.Student student = 3;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .restprotocolbuffers.Student student = 3;</code>
   */
  java.util.List<? extends org.techfrog.restprotocolbuffers.model.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .restprotocolbuffers.Student student = 3;</code>
   */
  org.techfrog.restprotocolbuffers.model.StudentOrBuilder getStudentOrBuilder(
      int index);
}
